code --install-extension \
  EditorConfig.EditorConfig \
  Equinusocio.vsc-material-theme \
  Hirse.vscode-ungit \
  James-Yu.latex-workshop \
  JuanBlanco.solidity \
  PKief.material-icon-theme \
  PeterJausovec.vscode-docker \
  Zignd.html-css-class-completion \
  christian-kohler.path-intellisense \
  codezombiech.gitignore \
  dbaeumer.vscode-eslint \
  eamodio.gitlens \
  esbenp.prettier-vscode \
  formulahendry.auto-close-tag \
  formulahendry.terminal \
  James-Yu.latex-workshop \
  jebbs.plantuml \
  joelday.docthis \
  michalkozubik.ui5-explorer \
  mikestead.dotenv \
  MS-CEINTL.vscode-language-pack-de \
  octref.vetur \
  redhat.java \
  vscjava.vscode-java-debug \
  vscjava.vscode-java-pack \
  vscjava.vscode-java-test \
  vscjava.vscode-maven \
  zhouronghui.propertylist \